=== chandru4664/Classworks_JEE2/XMLDemo/students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	    targetNamespace="http://www.htc.org/students" 
	    xmlns="http://www.htc.org/students" 
	    elementFormDefault="qualified">
	    
	    
<xsd:element name="students" type="students_ty"/>

<xsd:complexType name="students_ty">
<xsd:sequence>
<xsd:element name="student" type="student_ty"  minOccurs="1" maxOccurs="unbounded"/>
</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="student_ty">
<xsd:sequence>

<xsd:element name="studentid" type="id_ty"/>
<xsd:element name="studentname" type="xsd:string"/>
<xsd:element name="course" type="xsd:string"/>

</xsd:sequence>
</xsd:complexType>


<xsd:simpleType name="id_ty">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="s\d{3}"></xsd:pattern>
		</xsd:restriction>
	</xsd:simpleType>

</xsd:schema>

=== chandru4664/Classworks_JEE2/StAXDemo/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<students xmlns="http://www.htc.org/students" 
       xmlns:ns="http://www.w3.org/2001/XMLSchema-instance" 
       ns:schemaLocation="http://www.htc.org/students students.xsd">

<student>
<studentid>s109</studentid>
<studentname>xxx</studentname>
<course>java</course>
</student>

<student>
<studentid>s108</studentid>
<studentname>yyy</studentname>
<course>PHP</course>
</student>

</students>
